function [] = move_fig()
% move figure with arrow keys.
S.fh = figure('units','pixels',...
              'position',[500 500 200 260],...
              'menubar','none',...
              'name','move_fig',...
              'numbertitle','off',...
              'resize','off',...
              'keypressfcn',@fh_kpfcn);
S.tx = uicontrol('style','text',...
                 'units','pixels',...
                 'position',[60 120 80 20],...
                 'fontweight','bold'); 
guidata(S.fh,S)  